name = "discord-activity-server"
compatibility_date = "2025-05-26"
main = "src/index.ts"
compatibility_date = "2024-03-20" # Or your desired date
compatibility_flags = ["nodejs_compat"] # Ensure main entry point is defined

[site]
bucket = "../client" # Serves the client's static files from the worker

# [vars]
# Variables like CLIENT_ID, CLIENT_SECRET, GOOGLE_SHEET_ID, GOOGLE_API_KEY
# should be set as secrets in the Cloudflare dashboard or via 'wrangler secret put'.

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
