name = "discord-activity-server" # You can rename this if you like
compatibility_date = "2025-05-26" # Updated to a more recent date for v2 Node.js compat
assets = { not_found_handling = "single-page-application" }
main = "./worker/index.ts"
compatibility_flags = ["nodejs_compat"]

# Environment variable bindings for the worker
# For local development, create a .dev.vars file in the root of this project:
# DISCORD_CLIENT_ID="your_actual_discord_client_id"
# DISCORD_CLIENT_SECRET="your_actual_discord_client_secret"
# GOOGLE_SHEET_ID="your_actual_google_sheet_id"
# GOOGLE_API_KEY="your_actual_google_api_key"
#
# For production, use `wrangler secret put <VARIABLE_NAME>`
[vars]
DISCORD_CLIENT_ID = "your_discord_client_id_placeholder"
DISCORD_CLIENT_SECRET = "your_discord_client_secret_placeholder"
GOOGLE_SHEET_ID = "your_google_sheet_id_placeholder"
GOOGLE_API_KEY = "your_google_api_key_placeholder"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true