name = "discord-activity-server" # You can rename this if you like
compatibility_date = "2025-05-26" # Updated to a more recent date for v2 Node.js compat
assets = { not_found_handling = "single-page-application" }
main = "./worker/index.ts"
compatibility_flags = ["nodejs_compat"]

# Environment variable bindings for the worker
# For local development, create a .dev.vars file in the root of this project:
#DISCORD_CLIENT_ID="your_actual_discord_client_id"
#DISCORD_CLIENT_SECRET="your_actual_discord_client_secret"
#GOOGLE_SHEET_ID="your_actual_google_sheet_id"
#GOOGLE_API_KEY="your_actual_google_api_key"
#
# For production, use `wrangler secret put <VARIABLE_NAME>`
[vars]
#DISCORD_CLIENT_ID = meta.env.DISCORD_CLIENT_ID
#DISCORD_CLIENT_SECRET = meta.env.DISCORD_CLIENT_SECRET
#GOOGLE_SHEET_ID = meta.env.GOOGLE_SHEET_ID
#GOOGLE_API_KEY = meta.env.GOOGLE_API_KEY

# wrangler.toml (wrangler v4.16.1^)
[observability.logs]
enabled = true